version: 2

python:
  install:
    - path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libpod-markdown-perl
sphinx:
  configuration: doc/conf.py
